language: go
go: 
 - 1.15.6

script:
 - go test -race -coverprofile=coverage.txt -covermode=atomic ./tests/...

after_success:
 - bash <(curl -s https://codecov.io/bash)

- name: Codecov
  uses: codecov/codecov-action@v1.2.1
